language: node_js
node_js:
  - 5
script: npm test
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
deploy:
  provider: heroku
  api_key:
    secure: Pqs+vLsTaywfJvmspcR+nDJtEaWRFSI/WDdZjVLDwCUz5Q3o+B8RVcKIuh8YNUROeIG+F28LisRKlco99oivpruM1HdqmZ1f3H3pCP+cFY70Mhn2Wgp1loSIQRZh8NRY3RzTTbEwBIu/ePoiwlNN3kvlUITSgLHJOLJRt0Py02TPo7wFbmvjLpGrYoYY1bqWAy0aGomNEZkpnRMlCSn4TEV13FZ1F56xEjUtXpkWzeO7WpE1m3yPcgdbFcNDj1uR9QYmPuHGIDkO1PJqS+cW7UYH4ugimr/zgOOvxsQdH059M2EG3ExA8QSYAFEym2RTCqSygafSZ/M0dpaOm1ySYqheKZqjCw9LTgXWgx4IPYN/x59h+lF7VKz28olIqcRfXbhL+Dl+OC8VMZ5BCey/hhFhwaOPseLs/kIIeTy54uJaih2HokBqPEqKyST2t90z2PBf3n4ijl212I4EUFdCRZARoB5l1eM1G9OflH81K0CJ20FslbAEPvDpfrnHRrunb5cokAyVIkByFgShpmN9z2AxyNwpZxRAZby249Eq6mZrPX/B+/LK8cyWJKk8aMKmh5ZyAtYmCTWlzloYcfJfTVLZ7b/n20wdJklk8LO+ADM3mapUFq54aJQ+0JtaE/nLCW2rAOba8b89JdtWS7A3dDSJpeby/viMDXx13ppiByg=
  app: open2
notifications:
  email: false
