language: node_js
node_js:
  - 5
script: cd client && npm install && npm test && cd ../server && npm install && npm test
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
